# Generated by Django 5.1.3 on 2024-11-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_tag_id'),
        ('tags', '0002_remove_tag_title_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag_id',
            field=models.ManyToManyField(related_name='posts', to='tags.tag'),
        ),
    ]
