# Generated by Django 5.1.3 on 2024-11-20 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_tag_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
