# Generated by Django 5.1.3 on 2024-11-20 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_rename_tag_id_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article_pic',
            field=models.ImageField(blank=True, null=True, upload_to='article_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
