# Generated by Django 5.1.3 on 2024-11-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_read_time_alter_post_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article_pic',
            field=models.ImageField(default='article_pics/default.jpg', upload_to='article_pics'),
        ),
    ]
